language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_deploy:
  - cargo doc
  - cargo package

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: target/package/fiveo-$TRAVIS_TAG.crate
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"

after_deploy:
  - cargo publish --token "$CRATESIO_TOKEN"