[package]
name = "fiveo"
version = "0.3.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
description = "An approximate string matching library built with the web in mind"
license = "ISC"

[features]
webassembly = []

[profile.release]
debug = true